### ISSUE TITLE
got SyntaxError: Unexpected identifier with next.js

### ISSUE THREAD

**Issue by XinyiH** [mbrn/material-table#105]
Got this error when loading the index page

```
/testReact/node_modules/material-table/dist/material-table.js:1
(function (exports, require, module, __filename, __dirname) { import _objectSpread from "@babel/runtime/helpers/objectSpread";
                                                                     ^^^^^^^^^^^^^

SyntaxError: Unexpected identifier
    at new Script (vm.js:83:7)
    at createScript (vm.js:267:10)
    at Object.runInThisContext (vm.js:319:10)
    at Module._compile (internal/modules/cjs/loader.js:685:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:733:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:560:12)
    at Function.Module._load (internal/modules/cjs/loader.js:552:3)
    at Module.require (internal/modules/cjs/loader.js:658:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.material-table (/testReact/.next/server/static/development/pages/index.js:143:18)
    at __webpack_require__ (/testReact/.next/server/static/development/pages/index.js:23:31)
    at Module../pages/index.js (/testReact/.next/server/static/development/pages/index.js:107:72)
    at __webpack_require__ (/testReact/.next/server/static/development/pages/index.js:23:31)
    at Object.3 (/testReact/.next/server/static/development/pages/index.js:131:18)
    at __webpack_require__ (/testReact/.next/server/static/development/pages/index.js:23:31)
```

in page/index.js
```
import MaterialTable from 'material-table'

export default () => <div>Welcome to next.js!</div>
```

**Comment by mbrn** [comment]
Hi @XinyiH,

I didn't try material-table with nextjs. But i will try it asap.
