### ISSUE TITLE
"renderInput is not a function" in mui datepicker - v2.0.3

### ISSUE THREAD

**Issue by yaagesh** [mbrn/material-table#3129]
Uncaught TypeError: renderInput is not a function
    at PureDateInput (PureDateInput.js:27:1)
    at renderWithHooks (react-dom.development.js:14985:1)
    at updateForwardRef (react-dom.development.js:17044:1)
    at beginWork (react-dom.development.js:19098:1)
    at HTMLUnknownElement.callCallback (react-dom.development.js:3945:1)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:3994:1)
    at invokeGuardedCallback (react-dom.development.js:4056:1)
    at beginWork$1 (react-dom.development.js:23964:1)
    at performUnitOfWork (react-dom.development.js:22776:1)
    at workLoopSync (react-dom.development.js:22707:1)
    at renderRootSync (react-dom.development.js:22670:1)
    at performSyncWorkOnRoot (react-dom.development.js:22293:1)
    at react-dom.development.js:11327:1
    at unstable_runWithPriority (scheduler.development.js:468:1)
    at runWithPriority$1 (react-dom.development.js:11276:1)
    at flushSyncCallbackQueueImpl (react-dom.development.js:11322:1)
    at flushSyncCallbackQueue (react-dom.development.js:11309:1)
    at discreteUpdates$1 (react-dom.development.js:22420:1)
    at discreteUpdates (react-dom.development.js:3756:1)
    at dispatchDiscreteEvent (react-dom.development.js:5889:1)

**Comment by rallona** [comment]
I have this same problem

**Comment by andreymason** [comment]
Bro, try this

`
{ title: 'day', field: 'day',
      editComponent: props => <CustomDatePicker value={props.value} onChange={props.onChange} />
},
`

In CustomDatePicker file

`
const CustomDatePicker = (props: any) => {
    
    return (
        <TextField
        id="date"
        type="date"
        defaultValue={props.value}
        InputLabelProps={{
          shrink: true,
        }}
        onChange = {
            e => {
                props.onChange(e.target.value)
            }
        }
      />
    );
};

export default CustomDatePicker;
`
