### ISSUE TITLE
renderInput is not a function error with datePicker

### ISSUE THREAD

**Issue by rallona** [mbrn/material-table#3188]
# Guidelines

- #### Following the use of DatePicker [https://mui.com/x/react-date-pickers/date-picker/](https://mui.com/x/react-date-pickers/date-picker/)

- #### I have tried to recreate this code that is used for datepicker on mobileversion:

import * as React from 'react';
import dayjs, { Dayjs } from 'dayjs';
import TextField from '@mui/material/TextField';
import Stack from '@mui/material/Stack';
import { AdapterDayjs } from '@mui/x-date-pickers/AdapterDayjs';
import { LocalizationProvider } from '@mui/x-date-pickers/LocalizationProvider';
import { DatePicker } from '@mui/x-date-pickers/DatePicker';
import { MobileDatePicker } from '@mui/x-date-pickers/MobileDatePicker';
import { DesktopDatePicker } from '@mui/x-date-pickers/DesktopDatePicker';

export default function ResponsiveDatePickers() {
  const [value, setValue] = React.useState<Dayjs | null>(dayjs('2022-04-07'));

  return (
    <LocalizationProvider dateAdapter={AdapterDayjs}>
      <Stack spacing={3}>
        <MobileDatePicker
          label="For mobile"
          value={value}
          onChange={(newValue) => {
            setValue(newValue);
          }}
          renderInput={(params) => <TextField {...params} />}
        />
      
      </Stack>
    </LocalizationProvider>
  );
}

I get the error: **renderInput is not a function**

This is the error of te developer console in my browser:

_PureDateInput.js:36 Uncaught TypeError: renderInput is not a function
    at PureDateInput (PureDateInput.js:36:10)
    at renderWithHooks (react-dom.development.js:16305:18)
    at updateForwardRef (react-dom.development.js:19226:20)
    at beginWork (react-dom.development.js:21636:16)
    at HTMLUnknownElement.callCallback (react-dom.development.js:4164:14)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:4213:16)
    at invokeGuardedCallback (react-dom.development.js:4277:31)
    at beginWork$1 (react-dom.development.js:27451:7)
    at performUnitOfWork (react-dom.development.js:26557:12)
    at workLoopSync (react-dom.development.js:26466:5)
PureDateInput @ PureDateInput.js:36
renderWithHooks @ react-dom.development.js:16305
updateForwardRef @ react-dom.development.js:19226
beginWork @ react-dom.development.js:21636
callCallback @ react-dom.development.js:4164
invokeGuardedCallbackDev @ react-dom.development.js:4213
invokeGuardedCallback @ react-dom.development.js:4277
beginWork$1 @ react-dom.development.js:27451
performUnitOfWork @ react-dom.development.js:26557
workLoopSync @ react-dom.development.js:26466
renderRootSync @ react-dom.development.js:26434
recoverFromConcurrentError @ react-dom.development.js:25850
performConcurrentWorkOnRoot @ react-dom.development.js:25750
workLoop @ scheduler.development.js:266
flushWork @ scheduler.development.js:239
performWorkUntilDeadline @ scheduler.development.js:533
react-dom.development.js:18687 The above error occurred in the <ForwardRef(PureDateInput)> component:

    at PureDateInput (webpack-internal:///./node_modules/@mui/x-date-pickers/internals/components/PureDateInput.js:21:5)
    at MobileWrapper (webpack-internal:///./node_modules/@mui/x-date-pickers/internals/components/wrappers/MobileWrapper.js:22:7)
    at MobileDatePicker (webpack-internal:///./node_modules/@mui/x-date-pickers/MobileDatePicker/MobileDatePicker.js:44:98)
    at LocalizationProvider (webpack-internal:///./node_modules/@mui/x-date-pickers/LocalizationProvider/LocalizationProvider.js:30:81)
    at div
    at eval (webpack-internal:///./node_modules/@emotion/react/dist/emotion-element-6a883da9.browser.esm.js:53:66)
    at Grid (webpack-internal:///./node_modules/@mui/system/esm/Unstable_Grid/createGrid.js:75:73)
    at div
    at eval (webpack-internal:///./node_modules/@emotion/react/dist/emotion-element-6a883da9.browser.esm.js:53:66)
    at Container (webpack-internal:///./node_modules/@mui/system/esm/Container/createContainer.js:127:19)
    at form
    at Formik (webpack-internal:///./node_modules/formik/dist/formik.esm.js:1020:19)
    at ErrorBoundary (webpack-internal:///./src/CrearTurno.js:86:5)
    at CrearTurno (webpack-internal:///./src/CrearTurno.js:163:75)

React will try to recreate this component tree from scratch using the error boundary you provided, ErrorBoundary.
logCapturedError @ react-dom.development.js:18687
callback @ react-dom.development.js:18755
callCallback @ react-dom.development.js:13923
commitUpdateQueue @ react-dom.development.js:13944
commitLayoutEffectOnFiber @ react-dom.development.js:23364
commitLayoutMountEffects_complete @ react-dom.development.js:24688
commitLayoutEffects_begin @ react-dom.development.js:24674
commitLayoutEffects @ react-dom.development.js:24612
commitRootImpl @ react-dom.development.js:26823
commitRoot @ react-dom.development.js:26682
finishConcurrentRender @ react-dom.development.js:25892
performConcurrentWorkOnRoot @ react-dom.development.js:25809
workLoop @ scheduler.development.js:266
flushWork @ scheduler.development.js:239
performWorkUntilDeadline @ scheduler.development.js:533
react-dom.development.js:18687 The above error occurred in the <ForwardRef(PureDateInput)> component:

    at PureDateInput (webpack-internal:///./node_modules/@mui/x-date-pickers/internals/components/PureDateInput.js:21:5)
    at MobileWrapper (webpack-internal:///./node_modules/@mui/x-date-pickers/internals/components/wrappers/MobileWrapper.js:22:7)
    at MobileDatePicker (webpack-internal:///./node_modules/@mui/x-date-pickers/MobileDatePicker/MobileDatePicker.js:44:98)
    at LocalizationProvider (webpack-internal:///./node_modules/@mui/x-date-pickers/LocalizationProvider/LocalizationProvider.js:30:81)
    at div
    at eval (webpack-internal:///./node_modules/@emotion/react/dist/emotion-element-6a883da9.browser.esm.js:53:66)
    at Box (webpack-internal:///./node_modules/@mui/system/esm/createBox.js:36:72)
    at div
    at eval (webpack-internal:///./node_modules/@emotion/react/dist/emotion-element-6a883da9.browser.esm.js:53:66)
    at Container (webpack-internal:///./node_modules/@mui/system/esm/Container/createContainer.js:127:19)
    at form
    at Formik (webpack-internal:///./node_modules/formik/dist/formik.esm.js:1020:19)
    at ErrorBoundary (webpack-internal:///./src/CrearTurno.js:86:5)
    at CrearTurno (webpack-internal:///./src/CrearTurno.js:163:75)_

**To Reproduce**
You only have to copy the code that is available in the manual and run the app

**Comment by andreymason** [comment]
Bro, try this

`
{ title: 'day', field: 'day',
      editComponent: props => <CustomDatePicker value={props.value} onChange={props.onChange} />
    },
`

in CustomDatePicker file:

`const CustomDatePicker = (props: any) => {
    
    return (
        <TextField
        id="date"
        type="date"
        defaultValue={props.value}
        InputLabelProps={{
          shrink: true,
        }}
        onChange = {
            e => {
                props.onChange(e.target.value)
            }
        }
      />
    );
};

export default CustomDatePicker;`
