### ISSUE TITLE
fs module cant resolve in version 1.69.3

### ISSUE THREAD

**Issue by ranafaraznaru** [mbrn/material-table#3220]
**Describe the bug**
My React Version :  16.8.5
My React Dom Version : 16.8.5
My Material-UI core version : 4.10.2
My Material-Table Version: 1.69.3

i specially upgrade my react and dom version to above versions for meet with requirements of material-table 1.69.3 version
i am getting these two errors 

ERROR in ./node_modules/material-table/node_modules/jspdf/dist/jspdf.node.min.js
Module not found: Error: Can't resolve 'fs' in 'C:\Users\Rana Faraz\Desktop\progressay_front_end\node_modules\material-table\node_modules\jspdf\dist'

ERROR in ./app/assets/images/lessonbuilderstart.gif
Module build failed (from ./node_modules/image-webpack-loader/index.js):
Error: Command failed: C:\Users\Rana Faraz\Desktop\progressay_front_end\node_modules\gifsicle\vendor\gifsicle.exe --no-warnings --no-app-extensions --output C:\Users\RANAFA~1\AppData\Local\Temp\3be64f27-2fc1-46b2-bfa9-99df3af7cbc3 C:\Users\RANAFA~1\AppData\Local\Temp\d3a0de6a-ee10-4ce7-9392-fa469c63df41

    at C:\Users\Rana Faraz\Desktop\progressay_front_end\node_modules\exec-buffer\node_modules\execa\index.js:231:11
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)

the first error came after installing material-table version 1.69.3 before i was using 1.36.0 which was working fine but the features i need was available in 1.69.3 version

if i uninstall the material-table library then the second error is gone and first one also.

How to resolve this issue? i was facing this same issue (can't resolve fs) then i uninstall the library this error was not getting resolve. Now i am stuck again from 2 days so now i thought this is final thing asking from your guys for help before give up.

![image](https://github.com/mbrn/material-table/assets/36457463/6b1f44c9-1c67-4f8a-b780-684add5d1e9f)

- OS: windows 10
- Browser : chrome

**Comment by ranafaraznaru** [comment]
anyone can help?
